let pizzaJson = [
   {
      id: 1,
      name: 'Mozzarella',
      img: './img/pizzas/pizza.png',
      price: 149.45,
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      category: 4,
      rating: 7,
      description: 'The Mozzarella pizza is the best-selling in our establishment.',
   },
   {
      id: 2,
      name: 'Pepperoni',
      img: './img/pizzas/pizza2.png',
      price: 149.45,
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      category: 4,
      rating: 7,
      description:
         'Pepperoni pizza is one of the most traditional and beloved flavors among people of all ages.',
   },
   {
      id: 3,
      name: 'Four Cheeses',
      img: './img/pizzas/pizza3.png',
      price: 149.45,
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      category: 4,
      rating: 7,
      description:
         'Four Cheeses pizza is made with cheese imported from Switzerland, which gives it a different taste than normal.',
   },
   {
      id: 4,
      name: 'American',
      img: './img/pizzas/pizza4.png',
      price: 149.45,
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      category: 4,
      rating: 8,
      description: 'American pizza has some special things like spicy seasonings.',
   },
   {
      id: 5,
      name: 'Ice Cream',
      img: './img/pizzas/pizza5.png',
      price: 149.45,
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      category: 4,
      rating: 7,
      description:
         'The Ice Cream pizza has a difference: it is half sweet pizza and half ice cream.',
   },
   {
      id: 6,
      name: 'House Fashion',
      img: './img/pizzas/pizza6.png',
      price: 149.45,
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      category: 4,
      rating: 5,
      description: 'House Fashion pizza contains mushrooms and is vegan.',
   },
   {
      id: 7,
      name: 'Barbecue sausages',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/03c840b1ab6f4ccb84f5dc167e146598_366x366.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 3,
      rating: 6,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 8,
      name: 'Chocolate',
      img: './img/pizzas/pizza7.png',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 4,
      rating: 5,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 9,
      name: 'Chisoro fresh',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/02ca2561953b488993878d1f70e359de_366x366.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 4,
      rating: 5,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 10,
      name: 'Diablo',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/03c840b1ab6f4ccb84f5dc167e146598_366x366.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 4,
      rating: 7,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 11,
      name: 'Vegetables mix',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/d6c9f93ea37649ac923e9586c034a5a0_366x366.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 2,
      rating: 5,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 12,
      name: 'Hawaiian',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/c24bb8e55baa4ca68945459ac6afdf3e_760x760.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 1,
      rating: 9,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 13,
      name: 'Meat pizza',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/18dbb12240b041a191c9dc73c9c1f4ef_366x366.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 1,
      rating: 8,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 14,
      name: 'Curry chicken',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/c8ac7d2eb95b4bd0b8bc2f366415896c_760x760.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 4,
      rating: 8,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 15,
      name: 'Burger pizza',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/3a948b9d5af14d219e2c54282229755a_366x366.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 3,
      rating: 4,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 16,
      name: 'Double pepperoni',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/a96e936c158249e18c831bbcce677065_760x760.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 1,
      rating: 5,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
   {
      id: 17,
      name: 'Chicken ranch',
      img: 'https://dodopizza-a.akamaihd.net/static/Img/Products/e379c72af6c54f81b7b4e6ffbb2b1729_366x366.webp',
      sizes: ['320g', '530g', '860g'],
      types: ['S', 'M', 'L'],
      price: 149.45,
      category: 1,
      rating: 7,
      description: 'Chocolate pizza is the best-selling sweet pizza!',
   },
];
